set define off
delete dr_data_reconcile_metadata;
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (1,'BI_DIM_ADDRESS_DETAIL','AD_ADDRESS_ID','SELECT OBJECT_ID as AD_ADDRESS_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2304114)','','SELECT * FROM %API%.BI_DIM_ADDRESS_DETAIL WHERE AD_ADDRESS_ID <> 0',371246);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (2,'BI_DIM_BILLING_ACCOUNT','BA_BILLING_ACCOUNT_ID','SELECT OBJECT_ID as BA_BILLING_ACCOUNT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2365346)','OBJECT_STATE_ID<>23','SELECT * FROM %API%.BI_DIM_BILLING_ACCOUNT WHERE BA_BILLING_ACCOUNT_ID <> 0',377946);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (3,'BI_DIM_BILLING_BATCH','BB_ID','SELECT OBJECT_ID as BB_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2365946)','OBJECT_STATE_ID <> 23 AND OBJECT_STATE_ID <> 24','SELECT * FROM %API%.BI_DIM_BILLING_BATCH WHERE BB_ID <> 0',384346);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (4,'BI_DIM_BILLING_TRX','BT_ID','SELECT OBJECT_ID as BT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2365046)','OBJECT_STATE_ID <>23 AND OBJECT_STATE_ID <>24','SELECT * FROM %API%.BI_DIM_BILLING_TRX WHERE BT_ID <> 0',379646);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (5,'BI_DIM_BOND_TYPE_DETAIL','BT_BOND_MASTER_ID','SELECT OBJECT_ID as BT_BOND_MASTER_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3167646)','','SELECT * FROM %API%.BI_DIM_BOND_TYPE_DETAIL WHERE BT_BOND_MASTER_ID <> 0',439846);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (6,'BI_DIM_BUILDING_DETAIL','BD_BUILDING_ID','SELECT OBJECT_ID as BD_BUILDING_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE ((OBJECT_TYPE_ID=2261202) OR (OBJECT_TYPE_ID=371001))','','SELECT * FROM %API%.BI_DIM_BUILDING_DETAIL WHERE BD_BUILDING_ID <> 0',450948);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (7,'BI_DIM_COVERAGE_DETAIL','CO_COVERAGE_ID','SELECT OBJECT_ID as CO_COVERAGE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2309514)','','SELECT * FROM %API%.BI_DIM_COVERAGE_DETAIL WHERE CO_COVERAGE_ID <> 0',444048);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (8,'BI_DIM_COVERAGE_RULE','CR_RULE_ID','SELECT OBJECT_ID as CR_RULE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2240405)','','SELECT * FROM %API%.BI_DIM_COVERAGE_RULE WHERE CR_RULE_ID <> 0',381346);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (9,'BI_DIM_COVERED_ITEM','CI_ITEM_ID','SELECT OBJECT_ID as CI_ITEM_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2309514)','','SELECT * FROM %API%.BI_DIM_COVERED_ITEM WHERE CI_ITEM_ID <> 0',444148);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (10,'BI_DIM_CUSTOMER_DETAIL','CD_CUSTOMER_ID','SELECT OBJECT_ID as CD_CUSTOMER_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=12)','OBJECT_STATE_ID<>23','SELECT * FROM %API%.BI_DIM_CUSTOMER_DETAIL WHERE CD_CUSTOMER_ID <> 0',371146);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (11,'BI_DIM_FICHANGE_FITEM_DETAIL','FF_FITRANSACTION_ID','SELECT OBJECT_ID as FF_FITRANSACTION_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2365146)','','SELECT * FROM %API%.BI_DIM_FICHANGE_FITEM_DETAIL WHERE FF_FITRANSACTION_ID <> 0',379946);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (12,'BI_DIM_FITEM_CATEGORY','FC_SUB_CATEGORY_ID','SELECT OBJECT_ID as FC_SUB_CATEGORY_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2365246)','','SELECT * FROM %API%.BI_DIM_FITEM_CATEGORY WHERE FC_SUB_CATEGORY_ID <> 0',378046);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (13,'BI_DIM_OBJECT_STATE','OS_OBJECT_STATE_ID','SELECT OBJECT_STATE_ID as OS_OBJECT_STATE_ID, OBJECT_STATE_DISPLAY_NAME as OS_OBJECT_STATE_NAME FROM %MD%.OBJECT_STATE','','SELECT * FROM %API%.BI_DIM_OBJECT_STATE WHERE OS_OBJECT_STATE_ID <> 0',434546);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (14,'BI_DIM_OC_ASSET_DETAIL','ASD_ASSET_ID','SELECT o.OBJECT_ID as ASD_ASSET_ID, o.OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (o.OBJECT_TYPE_ID=3201146)','exists (select 1 from %API%.OBJECT_RELATION r, %SRCAPI%.dr_data_reconcile_object l where r.RELATION_OBJECT_ID = o.OBJECT_ID and r.OBJECT_RELATIONSHIP_BV_ID = 32258946 and r.OBJECT_TYPE_ID = 3201546 and r.RELATION_OBJECT_TYPE_ID = 3201146 and l.OBJECT_ID = r.OBJECT_ID and l.OBJECT_STATE_ID <> 23)','SELECT * FROM %API%.BI_DIM_OC_ASSET_DETAIL WHERE ASD_ASSET_ID <> 0',443646);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (15,'BI_DIM_OC_CATASTROPHE','CAT_CATASTROPHE_ID','SELECT OBJECT_ID as CAT_CATASTROPHE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3373846)','','SELECT * FROM %API%.BI_DIM_OC_CATASTROPHE WHERE CAT_CATASTROPHE_ID <> 0',447846);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (16,'BI_DIM_OC_CAUSE_OF_LOSS_TYPE','CLD_CAUSE_OF_LOSS_ID','SELECT OBJECT_ID as CLD_CAUSE_OF_LOSS_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3201546)','','SELECT * FROM %API%.BI_DIM_OC_CAUSE_OF_LOSS_TYPE WHERE CLD_CAUSE_OF_LOSS_ID <> 0',443446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (17,'BI_DIM_OC_CLAIM_COVERAGE','CC_CLAIM_COVERAGE_ID','SELECT OBJECT_ID as CC_CLAIM_COVERAGE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3335146)','(select count(1) from %API%.object_relation where relation_object_id = o.OBJECT_ID and object_relationship_bv_id = 32430946) > 0','SELECT * FROM %API%.BI_DIM_OC_CLAIM_COVERAGE WHERE CC_CLAIM_COVERAGE_ID <> 0',448646);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (18,'BI_DIM_OC_CLAIMANT_DETAIL','CLD_CLAIMANT_ID','SELECT OBJECT_ID as CLD_CLAIMANT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3200746)','','SELECT * FROM %API%.BI_DIM_OC_CLAIMANT_DETAIL WHERE CLD_CLAIMANT_ID <> 0',447246);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (19,'BI_DIM_OC_ENTITY_DETAIL','ETD_ENTITY_ID','SELECT o.OBJECT_ID as ETD_ENTITY_ID, o.OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (o.OBJECT_TYPE_ID=3200746)','OBJECT_STATE_ID = 75 and ( (select count(1) from %API%.object_relation r,%SRCAPI%.dr_data_reconcile_object l where r.object_relationship_bv_id = 34227846 and r.relation_object_id = o.object_id and l.object_id = r.object_id and l.object_state_id <> 23) > 0 or  (select count(1) from %API%.object_relation r,%SRCAPI%.dr_data_reconcile_object l where r.object_relationship_bv_id = 32464746 and r.relation_object_id = o.object_id and l.object_id = r.object_id and l.object_state_id <> 23) > 0 or  (select count(1) from %API%.object_relation r,%SRCAPI%.dr_data_reconcile_object l where r.object_relationship_bv_id = 33987846 and r.relation_object_id = o.object_id and l.object_id = r.object_id and l.object_state_id <> 23) > 0 or (select count(1) from %API%.object_relation r,%SRCAPI%.dr_data_reconcile_object l where r.object_relationship_bv_id = 33041848 and r.relation_object_id = o.object_id and l.object_id = r.object_id and l.object_state_id <> 23) > 0 or (select count(1) from %API%.object_relation r,%SRCAPI%.dr_data_reconcile_object l where r.object_relationship_bv_id = 32462846 and r.relation_object_id = o.object_id and l.object_id = r.object_id and l.object_state_id <> 23) > 0 or (select count(1) from %API%.object_relation r,%SRCAPI%.dr_data_reconcile_object l where r.object_relationship_bv_id = 32278246 and r.relation_object_id = o.object_id and l.object_id = r.object_id and l.object_state_id <> 23) > 0 )','SELECT * FROM %API%.BI_DIM_OC_ENTITY_DETAIL WHERE ETD_ENTITY_ID <> 0',443746);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (20,'BI_DIM_OC_INCIDENT_DETAIL','ID_INCIDENT_ID','SELECT o.OBJECT_ID as ID_INCIDENT_ID, o.OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (o.OBJECT_TYPE_ID=3201046)','exists ( select 1 from %SRCAPI%.dr_data_reconcile_object ils where ils.OBJECT_TYPE_ID = 3201246 and ils.PARENT_OBJECT_ID = o.OBJECT_ID and exists (select 1 from %SRCAPI%.dr_data_reconcile_object il where il.OBJECT_TYPE_ID = 3201546 and il.PARENT_OBJECT_ID = ils.OBJECT_ID) )','SELECT * FROM %API%.BI_DIM_OC_INCIDENT_DETAIL WHERE ID_INCIDENT_ID <> 0',447646);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (21,'BI_DIM_OC_LOB_DETAIL','LD_LOB_ID','SELECT OBJECT_ID as LD_LOB_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=24)','','SELECT * FROM %API%.BI_DIM_OC_LOB_DETAIL WHERE LD_LOB_ID <> 0',445046);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (22,'BI_DIM_OC_LOSS_TYPE','LTD_LOSS_TYPE_ID','SELECT OBJECT_ID as LTD_LOSS_TYPE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3201546)','','SELECT * FROM %API%.BI_DIM_OC_LOSS_TYPE WHERE LTD_LOSS_TYPE_ID <> 0',443546);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (23,'BI_DIM_PARTNER_ENTITY','PE_PARTNER_ID','SELECT OBJECT_ID as PE_PARTNER_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=63)','OBJECT_STATE_ID not in (23, 29305)','SELECT * FROM %API%.BI_DIM_PARTNER_ENTITY WHERE PE_PARTNER_ID <> 0',371346);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (24,'BI_DIM_POLICY_DETAIL','POD_POLICY_ID','SELECT OBJECT_ID as POD_POLICY_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=24)','','SELECT * FROM %API%.BI_DIM_POLICY_DETAIL WHERE POD_POLICY_ID <> 0',380446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (25,'BI_DIM_POLICY_TERM_DETAIL','POLT_ID','SELECT OBJECT_ID as POLT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2389401)','OBJECT_STATE_ID <> 23','SELECT * FROM %API%.BI_DIM_POLICY_TERM_DETAIL WHERE POLT_ID <> 0',453948);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (26,'BI_DIM_POLICY_TRANSACTION','PT_POLICY_TRANSACTION_ID','SELECT OBJECT_ID as PT_POLICY_TRANSACTION_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=629)','','SELECT * FROM %API%.BI_DIM_POLICY_TRANSACTION WHERE PT_POLICY_TRANSACTION_ID <> 0',378146);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (27,'BI_DIM_PRODUCER_PARTNER','PP_PRODUCER_ID','SELECT OBJECT_ID as PP_PRODUCER_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=309)','OBJECT_STATE_ID <> 23 AND NVL(%API%.pkg_db_readonly.fn_object_bv_path_get(111,111,OBJECT_ID,''211224.200909''), 4) <> 4','SELECT * FROM %API%.BI_DIM_PRODUCER_PARTNER WHERE PP_PRODUCER_ID <> 0',371746);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (28,'BI_DIM_SURETY_CUSTOMER_DETAIL','SCD_CUSTOMER_ID','SELECT OBJECT_ID as SCD_CUSTOMER_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=12)','','SELECT * FROM %API%.BI_DIM_SURETY_CUSTOMER_DETAIL WHERE SCD_CUSTOMER_ID <> 0',434246);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (29,'BI_DIM_USER_DETAIL','UD_USER_ID','SELECT OBJECT_ID as UD_USER_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=309)','OBJECT_STATE_ID<>23','SELECT * FROM %API%.BI_DIM_USER_DETAIL WHERE UD_USER_ID <> 0',371446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (30,'BI_DIM_VEHICLE_DETAIL','VD_VEHICLE_ID','SELECT OBJECT_ID as VD_VEHICLE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2270505)','','SELECT * FROM %API%.BI_DIM_VEHICLE_DETAIL WHERE VD_VEHICLE_ID <> 0',443948);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (31,'BI_FACT_AAIS_RECORD_DETAIL','AAIS_ID','SELECT OBJECT_ID as AAIS_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3371448)','','SELECT * FROM %API%.BI_FACT_AAIS_RECORD_DETAIL WHERE AAIS_ID <> 0',454948);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (32,'BI_FACT_ADDITIONAL_INSURED','AI_ID','select object_id as AI_ID from (SELECT object_id, decode(object_type_id, 380601, %API%.pkg_db_readonly.fn_object_bv_path_get(111, 111, object_id, ''22019101.21806301.21806001.21761201.21760901.28555404''), 2240805, %API%.pkg_db_readonly.fn_object_bv_path_get(111, 111, object_id, ''27385705.21761201.21760901.28555404''), 3363948, %API%.pkg_db_readonly.fn_object_bv_path_get(111, 111, object_id, ''32805548.21806301.21806001.21761201.21760901.28555404''), 381501, %API%.pkg_db_readonly.fn_object_bv_path_get(111, 111, object_id, ''32762348.21761201.21760901.28555404'')) pt_id FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID in (2240805,381501,3363948,380601) AND OBJECT_STATE_ID <> 24)) ai where exists (select 1 from %API%.dragon_policy_trx where policy_trx_id = ai.pt_id and policy_trx_object_state_id <> 23 and bi_process_date is not null )','','SELECT * FROM %API%.BI_FACT_ADDITIONAL_INSURED WHERE AI_ID <> 0',454748);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (33,'BI_FACT_BILLINGACCOUNTTRXSET','BTS_ID','SELECT OBJECT_ID as BTS_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2365946)','OBJECT_STATE_ID <> 23 and OBJECT_STATE_ID <> 24','SELECT * FROM %API%.BI_FACT_BILLINGACCOUNTTRXSET WHERE BTS_ID <> 0',446446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (34,'BI_FACT_CIF_DETAIL','CD_CIF_ID','SELECT OBJECT_ID as CD_CIF_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2276904)','','SELECT * FROM %API%.BI_FACT_CIF_DETAIL WHERE CD_CIF_ID <> 0',444846);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (35,'BI_FACT_COVERAGE_ATTRIBUTE','CA_ID','SELECT OBJECT_ID as CA_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2312914)','','SELECT * FROM %API%.BI_FACT_COVERAGE_ATTRIBUTE WHERE CA_ID <> 0',453748);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (36,'BI_FACT_COVERAGE_LEVEL_TRX','CLT_ID','SELECT OBJECT_ID as CLT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2297706)','','SELECT * FROM %API%.BI_FACT_COVERAGE_LEVEL_TRX WHERE CLT_ID <> 0',444248);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (37,'BI_FACT_CUSTOMER_FINANCE_STMT','CFS_FINANCE_STMT_ID','SELECT OBJECT_ID as CFS_FINANCE_STMT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3170846)','','SELECT * FROM %API%.BI_FACT_CUSTOMER_FINANCE_STMT WHERE CFS_FINANCE_STMT_ID <> 0',434346);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (38,'BI_FACT_DRAGON_USER_DETAIL','DUD_ID','SELECT OBJECT_ID as DUD_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=309)','OBJECT_STATE_ID <> 23','SELECT * FROM %API%.BI_FACT_DRAGON_USER_DETAIL WHERE DUD_ID <> 0',383646);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (39,'BI_FACT_FICHANGE_DETAIL','FCD_FICHANGE_ID','SELECT ro.OBJECT_ID as FCD_FICHANGE_ID, ro.OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object ro, %API%.object_bv_value ob WHERE ro.object_id = ob.object_id AND (ro.OBJECT_TYPE_ID=2365146) and ob.business_variable_id = 29709546 and ob.business_variable_value != ''401''','ro.OBJECT_STATE_ID != 23','SELECT * FROM %API%.BI_FACT_FICHANGE_DETAIL WHERE FCD_FICHANGE_ID <> 0',378246);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (40,'BI_FACT_FITEM_DETAIL','FID_FITEM_ID','SELECT OBJECT_ID as FID_FITEM_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2365246)','OBJECT_STATE_ID <> 23','SELECT * FROM %API%.BI_FACT_FITEM_DETAIL WHERE FID_FITEM_ID <> 0',379446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (41,'BI_FACT_FITRANSACTION_DETAIL','FT_ID','SELECT OBJECT_ID as FT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2365046)','OBJECT_STATE_ID <> 23 AND OBJECT_STATE_ID <> 24','SELECT * FROM %API%.BI_FACT_FITRANSACTION_DETAIL WHERE FT_ID <> 0',379846);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (42,'BI_FACT_FORM_DETAIL','FD_FORM_ID','SELECT OBJECT_ID as FD_FORM_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=325)','%API%.pkg_os_object.fn_object_type_get(199, 199, %API%.pkg_os_object_search.fn_object_get_parent_of_type(1100, 1100, OBJECT_ID, 629)) = 629 AND %API%.pkg_os_object.fn_object_state_get(199, 199, %API%.pkg_os_object_search.fn_object_get_parent_of_type(1100, 1100, OBJECT_ID, 629)) <> 23','SELECT * FROM %API%.BI_FACT_FORM_DETAIL WHERE FD_FORM_ID <> 0',450848);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (43,'BI_FACT_LIFE_POLICY_DETAIL','PD_POLICY_ID','SELECT OBJECT_ID as PD_POLICY_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=24)','','SELECT * FROM %API%.BI_FACT_LIFE_POLICY_DETAIL WHERE PD_POLICY_ID <> 0',448946);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (44,'BI_FACT_OC_CLAIM_DETAIL','CD_CLAIM_ID','SELECT OBJECT_ID as CD_CLAIM_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3203646)','','SELECT * FROM %API%.BI_FACT_OC_CLAIM_DETAIL WHERE CD_CLAIM_ID <> 0',447446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (45,'BI_FACT_OC_CLAIM_TRX_DETAIL','CT_ID','SELECT OBJECT_ID as CT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID IN (3331746, 3336746, 3337146, 3351946, 3395946, 3342246, 3336846, 3345646, 3396246, 3336946, 3337046, 3337746,3355448))','OBJECT_STATE_ID <> 23','SELECT * FROM %API%.BI_FACT_OC_CLAIM_TRX_DETAIL WHERE CT_ID <> 0',452448);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (46,'BI_FACT_OC_INCIDENTLOSS','CIL_INCIDENTLOSS_ID','SELECT OBJECT_ID as CIL_INCIDENTLOSS_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3201546)','OBJECT_STATE_ID <> 23','SELECT * FROM %API%.BI_FACT_OC_INCIDENTLOSS WHERE CIL_INCIDENTLOSS_ID <> 0',443346);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (47,'BI_FACT_OC_SUBCLAIM_DETAIL','SC_SUBCLAIM_ID','SELECT OBJECT_ID as SC_SUBCLAIM_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=3204946)','','SELECT * FROM %API%.BI_FACT_OC_SUBCLAIM_DETAIL WHERE SC_SUBCLAIM_ID <> 0',448446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (48,'BI_FACT_PARTNER_MGT_ACTIVITY','PMA_ID','SELECT OBJECT_ID as PMA_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=649)','','SELECT * FROM %API%.BI_FACT_PARTNER_MGT_ACTIVITY WHERE PMA_ID <> 0',405546);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (49,'BI_FACT_PARTNER_MGT_AGREEMENT','PMP_AGREEMENT_ID','SELECT OBJECT_ID as PMP_AGREEMENT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=306)','','SELECT * FROM %API%.BI_FACT_PARTNER_MGT_AGREEMENT WHERE PMP_AGREEMENT_ID <> 0',405746);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (50,'BI_FACT_PARTNER_MGT_LICENSE','PML_ID','SELECT OBJECT_ID as PML_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=342)','','SELECT * FROM %API%.BI_FACT_PARTNER_MGT_LICENSE WHERE PML_ID <> 0',405646);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (51,'BI_FACT_PIPELINE_DETAIL','PIP_QUOTE_ID','SELECT OBJECT_ID as PIP_QUOTE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=2276904)','','SELECT * FROM %API%.BI_FACT_PIPELINE_DETAIL WHERE PIP_QUOTE_ID <> 0',445246);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (52,'BI_FACT_POLICY_DETAIL','POF_POLICY_ID','SELECT OBJECT_ID as POF_POLICY_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=24)','','SELECT * FROM %API%.BI_FACT_POLICY_DETAIL WHERE POF_POLICY_ID <> 0',435546);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (53,'BI_FACT_POLICY_STAT_AGEING','POLICY_STAT_AGEING_ID','SELECT OBJECT_ID as POLICY_STAT_AGEING_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=3371146)','','SELECT * FROM %API%.BI_FACT_POLICY_STAT_AGEING WHERE POLICY_STAT_AGEING_ID <> 0',447046);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (54,'BI_FACT_POLICY_TRX_DETAIL','PT_ID','SELECT ro.OBJECT_ID as PT_ID, ro.OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object ro, %API%.object_bv_value ob WHERE ro.object_id = ob.object_id and ob.business_variable_id = 212161 and ob.business_variable_value is not null and (ro.OBJECT_TYPE_ID=629) ','OBJECT_STATE_ID not in (23, 24)','SELECT * FROM %API%.BI_FACT_POLICY_TRX_DETAIL WHERE PT_ID <> 0',371646);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (55,'BI_FACT_QUOTE_DETAIL','QD_QUOTE_ID','SELECT OBJECT_ID as QD_QUOTE_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2276904)','%API%.pkg_db_readonly.fn_evaluate_expression(111,111, OBJECT_ID, 9822846) = ''T'' AND OBJECT_STATE_ID != 23','SELECT * FROM %API%.BI_FACT_QUOTE_DETAIL WHERE QD_QUOTE_ID <> 0',371546);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (56,'BI_FACT_SURETY_BOND_DETAIL','BD_POLICY_ID','SELECT OBJECT_ID as BD_POLICY_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object o WHERE (OBJECT_TYPE_ID=629)','','SELECT * FROM %API%.BI_FACT_SURETY_BOND_DETAIL WHERE BD_POLICY_ID <> 0',434446);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (57,'BI_FACT_TASK_DETAIL','TD_TASK_ID','SELECT ro.OBJECT_ID as TD_TASK_ID, ro.OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object ro, %API%.object_bv_value ob, %API%.object_bv_value ob1 WHERE ro.object_id = ob.object_id and ro.object_id = ob1.object_id and (ro.OBJECT_TYPE_ID=62) and ob.business_variable_id = 28219405 and ob.business_variable_value = ''1'' and ob1.business_variable_id = 200709 and nvl(ob1.business_variable_value, ''0'') not in (''12546'',''12646'',''12946'')','ro.OBJECT_STATE_ID <>23','SELECT * FROM %API%.BI_FACT_TASK_DETAIL WHERE TD_TASK_ID <> 0',372046);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (58,'BI_FACT_UW_REFERRAL_DETAIL','URD_ID','SELECT OBJECT_ID as URD_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2240405)','TEMPLATE_OBJECT_ID is null','SELECT * FROM %API%.BI_FACT_UW_REFERRAL_DETAIL WHERE URD_ID <> 0',371946);
insert into dr_data_reconcile_metadata (id, table_name, pk_column, source_sql, source_sql_ext_condition, dest_sql, dm_id) values (59,'BI_FACT_UW_REFERRAL_TRACKER','URT_ID','SELECT OBJECT_ID as URT_ID, OBJECT_TYPE_ID FROM %SRCAPI%.dr_data_reconcile_object WHERE (OBJECT_TYPE_ID=2359401)','TEMPLATE_OBJECT_ID is null','SELECT * FROM %API%.BI_FACT_UW_REFERRAL_TRACKER WHERE URT_ID <> 0',380946);

--exclude deprecated tables
update dr_data_reconcile_metadata
set
active_tf = 0
where
	table_name not in ('BI_FACT_OC_CLAIM_DETAIL',
'BI_DIM_OC_CLAIM_COVERAGE',
'BI_FACT_OC_SUBCLAIM_DETAIL',
'BI_DIM_OC_ASSET_DETAIL',
'BI_DIM_BILLING_BATCH',
'BI_DIM_OC_ENTITY_DETAIL',
'BI_FACT_OC_INCIDENTLOSS',
'BI_DIM_OBJECT_STATE',
'BI_FACT_POLICY_STAT_AGEING',
'BI_FACT_ADDITIONAL_INSURED',
'BI_DIM_PARTNER_ENTITY',
'BI_DIM_PRODUCER_PARTNER',
'BI_FACT_DRAGON_USER_DETAIL',
'BI_DIM_USER_DETAIL',
'BI_DIM_OC_INCIDENT_DETAIL',
'BI_FACT_UW_REFERRAL_TRACKER',
'BI_DIM_POLICY_DETAIL',
'BI_FACT_UW_REFERRAL_DETAIL',
'BI_DIM_CUSTOMER_DETAIL',
'BI_DIM_POLICY_TERM_DETAIL',
'BI_FACT_QUOTE_DETAIL',
'BI_DIM_BILLING_ACCOUNT',
'BI_FACT_OC_CLAIM_TRX_DETAIL',
'BI_FACT_AAIS_RECORD_DETAIL',
'BI_FACT_POLICY_TRX_DETAIL',
'BI_FACT_BILLINGACCOUNTTRXSET',
'BI_FACT_FITRANSACTION_DETAIL',
'BI_DIM_BILLING_TRX',
'BI_FACT_FITEM_DETAIL',
'BI_FACT_FICHANGE_DETAIL',
'BI_FACT_TASK_DETAIL');
update dr_data_reconcile_metadata
set
  active_tf = 0
where
  table_name in 
		('BI_FACT_ADDITIONAL_INSURED',
		 'BI_FACT_QUOTE_DETAIL',
		 'BI_DIM_OC_ENTITY_DETAIL',
		 'BI_FACT_POLICY_STAT_AGEING'
			 );
			 
commit;