SP2-0158: unknown SET option "sqlb"

insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_POLICY',88459,88459,0,0,0);                                                                                  
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_PARTNER_AGREEMENT',3937,3937,0,0,0);                                                                         
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_PARTNER_AGREEMENT_PROD',552,552,0,0,0);                                                                      
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_SERVICE_GROUP_TERRITORY',25,27,2,0,8);                                                                       
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_USER_SERVICE_GROUP',90,90,0,0,0);                                                                            
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_POLICY_TRX',488049,488049,0,0,0);                                                                            
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_TREATY',,,,,);                                                                                               
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_REINSURANCE',,,,,);                                                                                          
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_USER',14232,14214,0,18,.13);                                                                                 
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BULLETIN',1,1,0,0,0);                                                                                        
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_PARTNER',8101,8101,0,0,0);                                                                                   
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_CUSTOMER',149336,149336,0,0,0);                                                                              
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_TASK',6741434,6741434,0,0,0);                                                                                

insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_LICENSE',2520,2520,0,0,0);                                                                                   
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_ASSOCIATED_AGENT',5528,5528,0,0,0);                                                                          
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_POLICY_QUOTE',97321,97321,0,0,0);                                                                            
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BILLINGACCOUNTTRXSET',2021593,2021593,0,0,0);                                                                
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_FITRANSACTION',3562762,3562762,0,0,0);                                                                       
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_FICHANGE',9651427,9651427,0,0,0);                                                                            
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_FITEM',3604451,3604451,0,0,0);                                                                               
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BOR_TRANSFER',980,1379,399,0,40.71);                                                                         
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_POLICY_TERM',109820,108931,0,889,.81);                                                                       
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_STATEMENTPROFILE',140031,140031,0,0,0);                                                                      
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_MASTER_ENTITY',283648,283648,0,0,0);                                                                            
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_PARTNER_AFFILIATION',1,1,0,0,0);                                                                             
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_CASH_ALLOCATION',,,,,);                                                                                      

insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_CALENDAR_EVENT',160,160,0,0,0);                                                                              
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_ROLLUP',1027576,1028968,1392,0,.14);                                                                         
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_ROLLUP_MEMBER',1517322,1519078,1756,0,.12);                                                                  
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_UW_TRIGGER_DETAIL',248397,252263,3866,0,1.56);                                                               
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_SUBCLAIM',3345,3345,0,0,0);                                                                                  
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_SUBCLAIM_TRX',8435,8435,0,0,0);                                                                              
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_CLAIM_TRX',8712,8712,0,0,0);                                                                                 
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_INCIDENTLOSS',,,,,);                                                                                         
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_UW_TRIGGER_SUMMARY',69143,71587,2444,0,3.53);                                                                
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BILLING_GL',1893813,1893813,0,0,0);                                                                          
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_MASTER_ADDRESS',195038,195038,0,0,0);                                                                           
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_SCHEDULED_INSTALLMENT',598985,598985,0,0,0);                                                                 
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_FUND_TRANS_REQ_TRY',214100,214100,0,0,0);                                                                    

insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_SUSPENSION',74682,74692,10,0,.01);                                                                           
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_ENTITY_VERSION',375248,375248,0,0,0);                                                                           
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_INCIDENT',1801,1801,0,0,0);                                                                                  
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_CLAIM',7855,7855,0,0,0);                                                                                     
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_INCIDENT_ENTITY',2292,2292,0,0,0);                                                                           
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_DOC_DLVRY_INSTRCTN',1185412,1185412,0,0,0);                                                                  
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_ASSOCIATED_TRANSACTION',116845,116845,0,0,0);                                                                
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BA_INSTALMENT',576302,576302,0,0,0);                                                                         
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BA_INSTALMENT_COMPONENT',588335,588335,0,0,0);                                                               
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_CATASTROPHE',4,4,0,0,0);                                                                                     
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_POLICY_TERM_PAYER',2397,2397,0,0,0);                                                                         
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_PAY_PROFILE',473850,473850,0,0,0);                                                                           
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_DISB_PROFILE',330346,373012,42666,0,12.92);                                                                  

insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_MASTER_PHONE_NUMBER',20435,20435,0,0,0);                                                                        
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_MASTER_EMAIL_ADDRESS',25648,25648,0,0,0);                                                                       
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_USER_ASGMT_PROFILE',,,,,);                                                                                   
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BA_SCHEDULEDPAYMENT',1590254,1590254,0,0,0);                                                                 
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BA_PAYMENTCOMPONENT',1601319,1601319,0,0,0);                                                                 
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_SERVICE_GROUP',27,27,0,0,0);                                                                                 
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_USER_LOAD_PROFILE',37,39,2,0,5.41);                                                                          
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_QUEUE_DEFINITION',7,7,0,0,0);                                                                                
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_QUEUE_CRITERIA',7,7,0,0,0);                                                                                  
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_QUEUE_GRP_ASGMT_CR',7,7,0,0,0);                                                                              
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_SUBSCRIBER',416188,416188,0,0,0);                                                                               
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BILL_PLAN',153135,153135,0,0,0);                                                                             
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_ENTITY_DETAIL_DATAMART',2011893,2011893,0,0,0);                                                                 

insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_CASHTRANSFERPROFILE',221125,221125,0,0,0);                                                                   
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_BOR_INCLUDED',1367,1367,0,0,0);                                                                              
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_PTP_PAYER',8033,7799,11,245,2.91);                                                                           
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'DRAGON_INCIDENT_ASSET',4797,4797,0,0,0);                                                                            
insert into dr_data_reconcile_dm_history (as_of_date, table_name, dragon_row_count, object_count, missing_rows, additional_rows, difference)values (to_date('03/30/2023','mm/dd/yyyy'),'ORM_ADDRESS_VERSION',197482,197482,0,0,0);                                                                          
Elapsed: 00:00:00.02
commit;
