--
PROMPT
PROMPT Alter &&MD_USER password
PROMPT
CONNECT &&MD_USER/&&MD_PASS@&&DB_NAME
ALTER USER &&MD_USER IDENTIFIED BY &&MD_PASS_SAVE;
--DISCONNECT
PROMPT
PROMPT Alter &&ST_USER password
PROMPT
CONNECT &&ST_USER/&&ST_PASS@&&DB_NAME
ALTER USER &&ST_USER IDENTIFIED BY &&ST_PASS_SAVE;
--DISCONNECT
PROMPT
PROMPT Alter &&API_USER password
PROMPT
CONNECT &&API_USER/&&API_PASS@&&DB_NAME
ALTER USER &&API_USER IDENTIFIED BY &&API_PASS_SAVE;
--DISCONNECT
--PROMPT
--PROMPT Checking connection &&DBA_USER @ &&DB_NAME
--PROMPT
--CONNECT &&DBA_USER/&&DBA_PASS@&&DB_NAME
DEFINE MD_PASS = &&MD_PASS_SAVE
DEFINE ST_PASS = &&ST_PASS_SAVE
DEFINE API_PASS = &&API_PASS_SAVE
DISCONNECT
--PROMPT
--
