--
PROMPT
PROMPT Alter &&MD_USER password
PROMPT
CONNECT &&MD_USER/&&MD_PASS@&&DB_NAME
ALTER USER &&MD_USER IDENTIFIED BY &&TP;
--DISCONNECT
PROMPT
PROMPT Alter &&ST_USER password
PROMPT
CONNECT &&ST_USER/&&ST_PASS@&&DB_NAME
ALTER USER &&ST_USER IDENTIFIED BY &&TP;
--DISCONNECT
PROMPT
PROMPT Alter &&API_USER password
PROMPT
CONNECT &&API_USER/&&API_PASS@&&DB_NAME
ALTER USER &&API_USER IDENTIFIED BY &&TP;
--DISCONNECT
--PROMPT
--PROMPT Checking connection &&DBA_USER @ &&DB_NAME
--PROMPT
--CONNECT &&DBA_USER/&&DBA_PASS@&&DB_NAME
DEFINE MD_PASS_SAVE = &&MD_PASS
DEFINE ST_PASS_SAVE = &&ST_PASS
DEFINE API_PASS_SAVE = &&API_PASS
DEFINE MD_PASS = &&TP
DEFINE ST_PASS = &&TP
DEFINE API_PASS = &&TP
DISCONNECT
--PROMPT
--
