--
PROMPT
PROMPT Checking connection &&MD_USER @ &&DB_NAME
PROMPT
CONNECT &&MD_USER/&&MD_PASS@&&DB_NAME
--DISCONNECT
PROMPT
PROMPT Checking connection &&ST_USER @ &&DB_NAME
PROMPT
CONNECT &&ST_USER/&&ST_PASS@&&DB_NAME
--DISCONNECT
PROMPT
PROMPT Checking connection &&API_USER @ &&DB_NAME
PROMPT
CONNECT &&API_USER/&&API_PASS@&&DB_NAME
PROMPT
PROMPT Checking connection &&DAP_USER @ &&DB_NAME
PROMPT
CONNECT &&DAP_USER/&&DAP_PASS@&&DB_NAME
--DISCONNECT
--PROMPT
--PROMPT Checking connection &&DBA_USER @ &&DB_NAME
--PROMPT
--CONNECT &&DBA_USER/&&DBA_PASS@&&DB_NAME
DISCONNECT
--PROMPT
--
