--
-- update_mapi_plsql.sql
-- Run MAPI PL/SQL scripts in order
-- This SQL script is generated by the Ant script
--
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
