--
-- update_st_dml.sql
-- Run ST DML scripts in order
-- This SQL script is generated by the Ant script
--
SET DEFINE OFF
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying st_dml/st_dml_new_tpr_OSPRODUCT-34013_SystemAttribute.sql
PROMPT
@@st_dml/st_dml_new_tpr_OSPRODUCT-34013_SystemAttribute.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
