--
-- update_mapi_log_dml.sql
-- Run MAPI LOG DML scripts in order
-- This SQL script is generated by the Ant script
--
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
