--
-- update_mapi_log_ddl.sql
-- Run MAPI LOG DDL scripts in order
-- This SQL script is generated by the Ant script
--
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
