--
-- update_st_dml.sql
-- Run ST DML scripts in order
-- This SQL script is generated by the Ant script
--
SET DEFINE OFF
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
