--
-- update_md_dml.sql
-- Run MD DML scripts in order
-- This SQL script is generated by the Ant script
--
SET DEFINE OFF
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
