UNDEFINE CORE_VERSION
UNDEFINE CLIENT_VERSION
UNDEFINE FROM_MD_USER
UNDEFINE FROM_ST_USER
UNDEFINE FROM_API_USER
UNDEFINE FROM_MAPI_USER
UNDEFINE FROM_MAPI_LOG_USER
UNDEFINE FROM_LEG_USER
UNDEFINE MAPI_VERSION
--
DEFINE CORE_VERSION = ''
DEFINE CLIENT_VERSION = 'PROD_7_2.01.01'
DEFINE PRODUCT_VERSION = ''
DEFINE FROM_MD_USER = 'DEMO_MD'
DEFINE FROM_ST_USER = 'DEMO_ST'
DEFINE FROM_API_USER = 'DEMO_API'
DEFINE FROM_MAPI_USER = 'DEMO_MAPI'
DEFINE FROM_MAPI_LOG_USER = 'DEMO_MAPI_LOG'
DEFINE FROM_LEG_USER = 'BASE_LEG'
DEFINE MAPI_VERSION = ''
