--
-- update_api_view.sql
-- Run API scripts in order
-- This SQL script is generated by the Ant script
--
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/VW_BI_EVENT_SUBSCRIPTION_LOG.sql
PROMPT
@@views/VW_BI_EVENT_SUBSCRIPTION_LOG.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/VW_OR_ELIGIBLE_REINSURANCE_COVERAGE.sql
PROMPT
@@views/VW_OR_ELIGIBLE_REINSURANCE_COVERAGE.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/VW_OR_ELIGIBLE_REINSURANCE_SUB_COVERAGE.sql
PROMPT
@@views/VW_OR_ELIGIBLE_REINSURANCE_SUB_COVERAGE.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/VW_OR_REINSURANCE_PROGRAM.sql
PROMPT
@@views/VW_OR_REINSURANCE_PROGRAM.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/VW_TASK_QUEUE_DASHBOARD.sql
PROMPT
@@views/VW_TASK_QUEUE_DASHBOARD.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/vw_or_arr_list_reinsurer.sql
PROMPT
@@views/vw_or_arr_list_reinsurer.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/vw_or_arrangement_list.sql
PROMPT
@@views/vw_or_arrangement_list.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROMPT Applying views/vw_renewal_image_create.sql
PROMPT
@@views/vw_renewal_image_create.sql
PROMPT
PROMPT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
